### ISSUE TITLE
Touchpad issues

### ISSUE THREAD

**Issue by MSzturc** [YBN-JUAN/T470s-OpenCore-EFI#2]
Hi YBN-JUAN,

i've had a look on your Touchpad configuration. The bug with the 3 keys right clicking is caused by bad acpi patching. Have a look at my ACPI Patches [here](https://github.com/MSzturc/Lenovo-T460-OpenCore/blob/master/ACPI/SSDT-KBRD.dsl). Btw. to get all fn keys working you could use [Thinkpad Assistant](https://github.com/MSzturc/ThinkpadAssistant)

**Comment by YBN-JUAN** [comment]
Great app! I've used your T480-KBRD SSDT, and the function keys work properly.
