### ISSUE TITLE
请问可以解决4k的问题吗

### ISSUE THREAD

**Issue by Wangchunsen1997** [YBN-JUAN/T470s-OpenCore-EFI#3]
我也是470s,自己换了4k屏后再也无法进入系统，bios无法更改dvmt，请问博主能通过改配置文件来实现对内屏4k的支持吗，专门为了黑苹果换的4k................
如果可以的话能留一个你的微信吗，可以有偿，谢谢了

**Comment by Wangchunsen1997** [comment]
如果博主看到了希望能回复我一下，自己被4k的问题折磨了几个月一直没得到解决，非常感谢！

**Comment by truongtam-fudosan** [comment]
I tried HDMI for 10.15.5, have prolem config about frambuffer.
So I did change. Pls check.
`                      <key>PciRoot(0x0)/Pci(0x2,0x0)</key>
			<dict>
				<key>AAPL,ig-platform-id</key>
				<data>AAAWWQ==</data>
				<key>AAPL,slot-name</key>
				<string>Built In</string>
				<key>device-id</key>
				<data>G1kAAA==</data>
				<key>device_type</key>
				<string>HDMI</string>
				<key>disable-external-gpu</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con0-enable</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con0-alldata</key>
                <data>AAAIAAIAAACYAAAA</data>
				<key>framebuffer-con1-enable</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con1-alldata</key>
                <data>AgQKAAAIAACHAQAA</data>
				<key>framebuffer-con2-enable</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con2-alldata</key>
                <data>AwYKAAAEAACHAQAA</data>
				<key>framebuffer-fbmem</key>
				<data>AACQAA==</data>
				<key>framebuffer-patch-enable</key>
				<data>AQAAAA==</data>
				<key>framebuffer-stolenmem</key>
				<data>AAAwAQ==</data>
				<key>model</key>
				<string>Intel HD Graphics 620</string>
			</dict>`

**Comment by Wangchunsen1997** [comment]
> I tried HDMI for 10.15.5, have prolem config about frambuffer.
> So I did change. Pls check.
> ` <key>PciRoot(0x0)/Pci(0x2,0x0)</key> <dict> <key>AAPL,ig-platform-id</key> <data>AAAWWQ==</data> <key>AAPL,slot-name</key> <string>Built In</string> <key>device-id</key> <data>G1kAAA==</data> <key>device_type</key> <string>HDMI</string> <key>disable-external-gpu</key> <data>AQAAAA==</data> <key>framebuffer-con0-enable</key> <data>AQAAAA==</data> <key>framebuffer-con0-alldata</key> <data>AAAIAAIAAACYAAAA</data> <key>framebuffer-con1-enable</key> <data>AQAAAA==</data> <key>framebuffer-con1-alldata</key> <data>AgQKAAAIAACHAQAA</data> <key>framebuffer-con2-enable</key> <data>AQAAAA==</data> <key>framebuffer-con2-alldata</key> <data>AwYKAAAEAACHAQAA</data> <key>framebuffer-fbmem</key> <data>AACQAA==</data> <key>framebuffer-patch-enable</key> <data>AQAAAA==</data> <key>framebuffer-stolenmem</key> <data>AAAwAQ==</data> <key>model</key> <string>Intel HD Graphics 620</string> </dict>`

hello,I meet some problems,would u help me,sorry,my english is bad,
